/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tablepert8;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author excee
 */
public class Table extends javax.swing.JFrame {

    private Object NoBonusRB;
    private Object BonusRB;

    
    public Table() {
        initComponents();
        initListeners();
        initButtonGroup();
    }
    
    private void initButtonGroup() {
        ButtonGroup ButtonGroup = new ButtonGroup();
        buttonGroup.add(BonusRb);
        buttonGroup.add(NoRb);
    }
    
    private void initListeners() {
        // Action Listener untuk tombol Tambah
        TambahBtn.addActionListener(evt -> tambahData());

        // Action Listener untuk tombol Hapus
        HapusBtn.addActionListener(evt -> hapusData());
    }
    
    private void tambahData() {
        // Pastikan tabel menggunakan DefaultTableModel
        DefaultTableModel model = (DefaultTableModel) Table.getModel();

        // Ambil data dari input user
        String produk = ProdukTF.getText();
        String merk = MerkTF.getText();
        String tipe = TipeTF.getText();
        String jumlah = JumlahTF.getText();
        String bonus = BonusRb.isSelected() ? "Bonus" : "No Bonus";
        String ecer = EcerChck.isSelected() ? "Ya" : "Tidak";

        // Validasi input
        if (produk.isEmpty() || merk.isEmpty() || tipe.isEmpty() || jumlah.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua field!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tambahkan data ke tabel
        model.addRow(new Object[]{produk, merk, tipe, jumlah, bonus, ecer});

        // Bersihkan input
        clearFields();
    }
    
    private void hapusData() {
        // Pastikan tabel menggunakan DefaultTableModel
        DefaultTableModel model = (DefaultTableModel) Table.getModel();

        // Ambil baris yang dipilih
        int selectedRow = Table.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Hapus baris yang dipilih
        model.removeRow(selectedRow);
    }
    
    // Metode untuk membersihkan field input
    private void clearFields() {
        ProdukTF.setText("");
        MerkTF.setText("");
        TipeTF.setText("");
        JumlahTF.setText("");
        BonusRb.setSelected(false);
        NoRb.setSelected(false);
        EcerChck.setSelected(false);
    }

    // Metode main untuk menjalankan aplikasi

    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        ProdukTXT = new javax.swing.JLabel();
        MerkTXT = new javax.swing.JLabel();
        TipeTXT = new javax.swing.JLabel();
        JumlahTXT = new javax.swing.JLabel();
        ProdukTF = new javax.swing.JTextField();
        MerkTF = new javax.swing.JTextField();
        TipeTF = new javax.swing.JTextField();
        JumlahTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        TambahBtn = new javax.swing.JButton();
        HapusBtn = new javax.swing.JButton();
        BonusRb = new javax.swing.JRadioButton();
        NoRb = new javax.swing.JRadioButton();
        EcerChck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProdukTXT.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ProdukTXT.setText("Produk");

        MerkTXT.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        MerkTXT.setText("Merk");

        TipeTXT.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TipeTXT.setText("Tipe");

        JumlahTXT.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        JumlahTXT.setText("Jumlah");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Produk", "Merk", "Tipe", "Jumlah", "Bundle", "Eceran"
            }
        ));
        jScrollPane1.setViewportView(Table);

        TambahBtn.setText("Tambahkan");
        TambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahBtnActionPerformed(evt);
            }
        });

        HapusBtn.setText("Hapus");
        HapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBtnActionPerformed(evt);
            }
        });

        buttonGroup.add(BonusRb);
        BonusRb.setText("Bonus");
        BonusRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonusRbActionPerformed(evt);
            }
        });

        buttonGroup.add(NoRb);
        NoRb.setText("No Bonus");

        EcerChck.setText("Eceran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JumlahTXT)
                            .addComponent(ProdukTXT)
                            .addComponent(MerkTXT)
                            .addComponent(TipeTXT))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ProdukTF, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                .addComponent(TipeTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MerkTF, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TambahBtn)
                                .addGap(18, 18, 18)
                                .addComponent(HapusBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BonusRb)
                                .addGap(18, 18, 18)
                                .addComponent(NoRb))
                            .addComponent(EcerChck)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProdukTXT)
                        .addGap(18, 18, 18)
                        .addComponent(MerkTXT)
                        .addGap(22, 22, 22)
                        .addComponent(TipeTXT)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JumlahTXT)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TambahBtn)
                                .addComponent(HapusBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProdukTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MerkTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BonusRb)
                                .addComponent(NoRb)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EcerChck))
                        .addGap(18, 18, 18)
                        .addComponent(JumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusBtnActionPerformed

    private void BonusRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BonusRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BonusRbActionPerformed

    private void TambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BonusRb;
    private javax.swing.JCheckBox EcerChck;
    private javax.swing.JButton HapusBtn;
    private javax.swing.JTextField JumlahTF;
    private javax.swing.JLabel JumlahTXT;
    private javax.swing.JTextField MerkTF;
    private javax.swing.JLabel MerkTXT;
    private javax.swing.JRadioButton NoRb;
    private javax.swing.JTextField ProdukTF;
    private javax.swing.JLabel ProdukTXT;
    private javax.swing.JTable Table;
    private javax.swing.JButton TambahBtn;
    private javax.swing.JTextField TipeTF;
    private javax.swing.JLabel TipeTXT;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
